### ISSUE TITLE
Support a parameter that holds an optional list of CIDR blocks or IP addresses to add to the allow list

### ISSUE THREAD

**Issue by rajbos** [peter-murray/github-ip-allow-list-action#1]
Use case:
- We have a GHES (Enterprise Server) instance and a GHEC (Enterprise Cloud) environment. The latter holds our actions forks following [best practices](https://devopsjournal.io/blog/2021/02/06/GitHub-Actions-Forking-Repositories). We want to lock down our GHEC environment so that our user only can connect to it from the internal (VPN) network (Big corp policies). 
- We want to use GitHub Connect from GHES to GHEC to enable the internal actions usage from GHEC
- Locking down GHEC means adding our internal CIDR blocks to the Allow List

Proposal:
- Add a parameter to this action to load the CIDR blocks to add from a list or a json file that the user can provide

**Comment by peter-murray** [comment]
I have released an updated version `v1.1` and updated the `v1` tag to also point at it as the changes were additive here.

Check out the README.md for an example and the updated parameters.

Please provide any feedback.

**Comment by rajbos** [comment]
Awesome! Thanks 👍
